name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish_pages:
        name: Build and Publish Page
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Install Deps
              run: npm i

            - name: Build
              run: npm run build     
              env:
                BASE_URL: "/keyblind/"

            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: pages
                  FOLDER: ./dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SKIP_EMPTY_COMMITS: true
                  MESSAGE: "Build: ({sha}) {msg}"
